# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기

train_over = pd.read_csv('train_over_A.csv',encoding='CP949')
#train_over = pd.read_csv('train_over_B.csv',encoding='CP949')
train_over = train_over.iloc[:,1:]

test_over = pd.read_csv('test_over_A.csv',encoding='CP949')
test_over = test_over.iloc[:,1:]
train_over.shape, test_over.shape

((56234, 114), (13775, 114))

In [3]:
train_over = train_over.loc[:,['dv1','dv2','dv4','dv3','dv15','CITY','dv17',
                            'M_WK_TIME','dv12','dv8','dv5','dv11','dv7',
                            'HW_S_R','dv14','dv20','M_SUI_CON']]

test_over = test_over.loc[:,['dv1','dv2','dv4','dv3','dv15','CITY','dv17',
                            'M_WK_TIME','dv12','dv8','dv5','dv11','dv7',
                            'HW_S_R','dv14','dv20','M_SUI_CON']]


train_over.shape, test_over.shape

((56234, 17), (13775, 17))

In [4]:
# 시도[CITY]
## 각 도시들을 1~17로 MAPPING 
print(train_over.loc[:,'CITY'].value_counts())
train_over[['CITY']] = train_over[['CITY']].replace({'경기':1, 
                                     '서울':2,
                                     '부산':3,
                                     '경남':4,
                                     '인천':5,
                                     '경북':6,
                                     '대구':7,
                                     '충남':8,
                                     '전남':9,
                                     '전북':10,
                                     '광주':11,
                                     '충북':12,
                                     '대전':13,
                                     '강원':14,
                                     '울산':15,
                                     '제주':16,
                                     '세종':17})
print(train_over.loc[:,'CITY'].value_counts())

경기    12531
서울     8747
부산     3442
경남     3405
인천     3154
대구     2908
경북     2864
충남     2621
전북     2334
충북     2286
전남     2281
광주     2194
대전     2149
강원     2033
울산     1705
제주     1105
세종      475
Name: CITY, dtype: int64
1     12531
2      8747
3      3442
4      3405
5      3154
7      2908
6      2864
8      2621
10     2334
12     2286
9      2281
11     2194
13     2149
14     2033
15     1705
16     1105
17      475
Name: CITY, dtype: int64


In [5]:
# 시도[CITY]
## 각 도시들을 1~17로 MAPPING 
print(test_over.loc[:,'CITY'].value_counts())
test_over[['CITY']] = test_over[['CITY']].replace({'경기':1, 
                                     '서울':2,
                                     '부산':3,
                                     '경남':4,
                                     '인천':5,
                                     '경북':6,
                                     '대구':7,
                                     '충남':8,
                                     '전남':9,
                                     '전북':10,
                                     '광주':11,
                                     '충북':12,
                                     '대전':13,
                                     '강원':14,
                                     '울산':15,
                                     '제주':16,
                                     '세종':17})
print(test_over.loc[:,'CITY'].value_counts())

경기    3068
서울    2049
경남     848
부산     819
인천     804
대구     774
경북     665
전남     619
충남     605
전북     583
대전     541
광주     535
강원     513
충북     490
울산     447
제주     290
세종     125
Name: CITY, dtype: int64
1     3068
2     2049
4      848
3      819
5      804
7      774
6      665
9      619
8      605
10     583
13     541
11     535
14     513
12     490
15     447
16     290
17     125
Name: CITY, dtype: int64


In [6]:
# 데이터 팩터화
train_over['dv1'] = train_over['dv1'].astype('category')
train_over['dv2'] = train_over['dv2'].astype('category')
train_over['dv4'] = train_over['dv4'].astype('category')
train_over['dv3'] = train_over['dv3'].astype('category')
train_over['dv15'] = train_over['dv15'].astype('category')
train_over['CITY'] = train_over['CITY'].astype('category')
train_over['dv17'] = train_over['dv17'].astype('category')
#train_over['M_WK_TIME'] = train_over['M_WK_TIME'].astype('category')
train_over['dv12'] = train_over['dv12'].astype('category')
train_over['dv8'] = train_over['dv8'].astype('category')
train_over['dv5'] = train_over['dv5'].astype('category')
train_over['dv11'] = train_over['dv11'].astype('category')
train_over['dv7'] = train_over['dv7'].astype('category')
train_over['HW_S_R'] = train_over['HW_S_R'].astype('category')
train_over['dv14'] = train_over['dv14'].astype('category')
train_over['dv20'] = train_over['dv20'].astype('category')
train_over['M_SUI_CON'] = train_over['M_SUI_CON'].astype('category')
train_over.dtypes

dv1          category
dv2          category
dv4          category
dv3          category
dv15         category
CITY         category
dv17         category
M_WK_TIME     float64
dv12         category
dv8          category
dv5          category
dv11         category
dv7          category
HW_S_R       category
dv14         category
dv20         category
M_SUI_CON    category
dtype: object

In [7]:
# 데이터 팩터화
test_over['dv1'] = test_over['dv1'].astype('category')
test_over['dv2'] = test_over['dv2'].astype('category')
test_over['dv4'] = test_over['dv4'].astype('category')
test_over['dv3'] = test_over['dv3'].astype('category')
test_over['dv15'] = test_over['dv15'].astype('category')
test_over['CITY'] = test_over['CITY'].astype('category')
test_over['dv17'] = test_over['dv17'].astype('category')
#test_over['M_WK_TIME'] = test_over['M_WK_TIME'].astype('category')
test_over['dv12'] = test_over['dv12'].astype('category')
test_over['dv8'] = test_over['dv8'].astype('category')
test_over['dv5'] = test_over['dv5'].astype('category')
test_over['dv11'] = test_over['dv11'].astype('category')
test_over['dv7'] = test_over['dv7'].astype('category')
test_over['HW_S_R'] = test_over['HW_S_R'].astype('category')
test_over['dv14'] = test_over['dv14'].astype('category')
test_over['dv20'] = test_over['dv20'].astype('category')
test_over['M_SUI_CON'] = test_over['M_SUI_CON'].astype('category')
test_over.dtypes

dv1          category
dv2          category
dv4          category
dv3          category
dv15         category
CITY         category
dv17         category
M_WK_TIME     float64
dv12         category
dv8          category
dv5          category
dv11         category
dv7          category
HW_S_R       category
dv14         category
dv20         category
M_SUI_CON    category
dtype: object

In [8]:
# 결측치 있는지 확인 --> 결측치 없음
print(train_over.shape, test_over.shape)
train_over = train_over.dropna(axis=0)
test_over = test_over.dropna(axis=0)
print(train_over.shape, test_over.shape)

(56234, 17) (13775, 17)
(56234, 17) (13775, 17)


# Train/test Split

In [9]:
'''
Train과 Test는 기존 R로 분할을 했었기에
X와 Y에 대해서만 분리를 진행한다.
'''

# Train_over
#feature_columns = list(train_over.columns.difference(['M_SUI_CON']))
feature_columns = list(train_over.columns[:-1])
train_x = train_over[feature_columns]
train_y = train_over[['M_SUI_CON']]
test_x = test_over[feature_columns]
test_y = test_over[['M_SUI_CON']]



print(train_x.shape, train_y.shape, test_x.shape, test_y.shape)

(56234, 16) (56234, 1) (13775, 16) (13775, 1)


# Logistic Regression Modeling

In [10]:
# 각 지표 구하는 함수 구현
from sklearn.metrics import confusion_matrix

def model_evaluation(label, predict):
    cf_matrix = confusion_matrix(label, predict)
    Accuracy = (cf_matrix[0][0] + cf_matrix[1][1]) / sum(sum(cf_matrix))
    Precision = cf_matrix[1][1] / (cf_matrix[1][1] + cf_matrix[0][1])
    Recall = cf_matrix[1][1] / (cf_matrix[1][1] + cf_matrix[1][0])
    Specificity = cf_matrix[0][0] / (cf_matrix[0][0] + cf_matrix[0][1])
    F1_Score = (2 * Recall * Precision) / (Recall + Precision)
    
    return Accuracy, Precision, Recall, Specificity, F1_Score

In [11]:
len(feature_columns)

16

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

performance_df = pd.DataFrame(columns=['feature_num','Accuracy', 'Precision', 'Recall', 'Specificity', 'F1_Score'])



for i in range(0, len(feature_columns),1):

    train_x_final2 = train_x.loc[:,feature_columns]
    train_y_final2 = train_y
    test_x_final2 = test_x.loc[:,feature_columns]
    test_y_final2 = test_y
    #print(train_x_final2.shape, test_x_final2.shape)

    log_reg2 = LogisticRegression()
    log_reg2.fit(train_x_final2, train_y_final2)

    pred_y_final2 = log_reg2.predict(test_x_final2) #test_data넣어보기
    pred_y_final2
    
    print(confusion_matrix(test_y_final2, pred_y_final2))
    
    feature_num_tmp = len(feature_columns)
    accuracy_tmp = model_evaluation(test_y_final2, pred_y_final2)[0]
    precision_tmp = model_evaluation(test_y_final2, pred_y_final2)[1]
    recall_tmp = model_evaluation(test_y_final2, pred_y_final2)[2]
    specificity_tmp = model_evaluation(test_y_final2, pred_y_final2)[3]
    f1score_tmp = model_evaluation(test_y_final2, pred_y_final2)[4]
    
    performance_df = performance_df.append(
        pd.DataFrame([[feature_num_tmp, accuracy_tmp, precision_tmp, recall_tmp, specificity_tmp, f1score_tmp]], 
                   columns=['feature_num','Accuracy', 'Precision', 'Recall', 'Specificity', 'F1_Score']), ignore_index=True)


    feature_columns.pop()

c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was 

[[8761 3288]
 [ 477 1249]]
[[8774 3275]
 [ 488 1238]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[8846 3203]
 [ 500 1226]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[8820 3229]
 [ 495 1231]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[8842 3207]
 [ 495 1231]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9094 2955]
 [ 529 1197]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9109 2940]
 [ 514 1212]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9667 2382]
 [ 590 1136]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9659 2390]
 [ 585 1141]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9647 2402]
 [ 579 1147]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9951 2098]
 [ 759  967]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[9951 2098]
 [ 759  967]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[6483 5566]
 [ 715 1011]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[7047 5002]
 [ 846  880]]


c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\sungs\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[4447 7602]
 [ 525 1201]]
[[4447 7602]
 [ 525 1201]]


In [14]:
performance_df_sorting = performance_df.sort_values(by='feature_num')
performance_df_sorting.reset_index(drop=True, inplace=True)
performance_df_sorting

feature_num  Accuracy  Precision    Recall  Specificity  F1_Score
0            1  0.410018   0.136431  0.695829     0.369076  0.228132
1            2  0.410018   0.136431  0.695829     0.369076  0.228132
2            3  0.575463   0.149609  0.509849     0.584862  0.231335
3            4  0.544029   0.153718  0.585747     0.538053  0.243526
4            5  0.792595   0.315498  0.560255     0.825878  0.403674
5            6  0.792595   0.315498  0.560255     0.825878  0.403674
6            7  0.783593   0.323190  0.664542     0.800647  0.434882
7            8  0.784029   0.323138  0.661066     0.801643  0.434088
8            9  0.784247   0.322911  0.658169     0.802307  0.433257
9           10  0.749256   0.291908  0.702202     0.755996  0.412385
10          11  0.747078   0.288295  0.693511     0.754751  0.407281
11          12  0.731252   0.277377  0.713210     0.733837  0.399416
12          13  0.729655   0.276009  0.713210     0.732011  0.397995
13          14  0.731180   0.276812  0.710313     0.734169  0.398375
14          15  0.726824   0.274319  0.717265     0.728193  0.396858
15          16  0.726679   0.275292  0.723638     0.727114  0.398850